name: render
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - uses: actions/checkout@v4

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R packages
      - uses: r-lib/actions/setup-r-dependencies@v2

      # scrape with R sript
      - name: Fetch latest data
      run: Rscript scrape.R

      # auto commit updates
      - uses: stefanzweifel/git-auto-commit-action@v5
